#include <iostream>

int main() {

    try {
        int a = 10;
    }
    catch(std::runtime_error err) {
        ;
    }

    return 0;

}